//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneDBEntities : DbContext
    {
        public kutuphaneDBEntities()
            : base("name=kutuphaneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLISLEMLER> TBLISLEMLERs { get; set; }
        public virtual DbSet<TBLKISILER> TBLKISILERs { get; set; }
        public virtual DbSet<TBLKITAPLAR> TBLKITAPLARs { get; set; }
    }
}
