//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAPLAR
    {
        public int kitapID { get; set; }
        public string kitapBaslik { get; set; }
        public string kitapISBN { get; set; }
        public string kitapYayinYili { get; set; }
        public Nullable<decimal> kitapFiyat { get; set; }
        public string kitapDurum { get; set; }
        public Nullable<int> kitapIslem { get; set; }
    
        public virtual TBLISLEMLER TBLISLEMLER { get; set; }
    }
}
